name: Build Ride Request

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  call-build:
    uses: hendafarhani/github-actions-workflows/.github/workflows/maven-build.yml@main
    with:
      java_version: "21"
      maven_goal: "verify"
