name: Build Ride Request

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  call-build:
    uses: hendafarhani/microGo/.github/workflows/maven-build.yml@247bd1598dea8fc8b2b3dd1d9d474607fd9d5bd2
    with:
      java_version: "21"
      maven_goal: "verify"
