name: Sonar Ride Request

on:
  workflow_run:
    workflows: ["Build Ride Request"]
    types: [completed]
  workflow_dispatch:

jobs:
  sonar:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: hendafarhani/microGo/.github/workflows/sonar-analysis.yml@605ffc6677d5ae5df8d7b4500f30f2256705f107
    with:
      java_version: "21"
      sonar_project_key: "hendafarhani_ride-request"
      sonar_organization: "hendafarhani"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
