name: Sonar Ride Request

on:
  workflow_run:
    workflows: ["Build Ride Request"]
    types: [completed]
  workflow_dispatch:

jobs:
  sonar:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: hendafarhani/github-actions-workflows/.github/workflows/sonar.yml@main
    with:
      java_version: "21"
      sonar_project_key: "hendafarhani_ride-request"
      sonar_organization: "hendafarhani"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
